app/urls.py
from django.conf.urls import patterns, url

from app import views

urlpatterns = patterns(
    '',
    url('^$', views.index, name='index'),
    url('^top/$', views.top, name='top'),
    url('^quote/(?P<quote_id>\d+)/$', views.detail, name='detail'),
    url('^tag/(?P<tag_text>\w+)/$', views.tag, name='tag'),
    url('^user/(?P<username>\w+)/$', views.user, name='user'),
    url('^search/$', views.search, name='search'),
    url('^signup/$', views.signup, name='signup'),
    url('^login/$', views.log_in, name='login'),
    url('^logout/$', views.log_out, name='logout'),
    url('^submit/$', views.submit, name='submit'),
    )

qdb/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^password_required/$', 'password_required.views.login'),
    url(r'', include('app.urls', namespace='app')),
    )

app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Quote Database</title>

    <!-- Bootstrap -->
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'app/css/bootstrap.min.css' %}">

  </head>
  <body>
    <a href="{% url 'app:index' %}">Quote Database</a> | <a href="{% url 'app:top' %}">Top Quotes</a> | <a href="{% url 'app:submit' %}">Submit</a>{% if user.is_authenticated %} | <a href="{% url 'app:user' user.username %}">{{user.username}}</a> | <a href="{% url 'app:logout' %}">Log Out</a>{% else %} | <a href="{% url 'app:signup' %}">Sign Up</a> | <a href="{% url 'app:login' %}">Log In</a>{% endif %} | <form method="GET" action="{% url 'app:search' %}"><input type="text" name="q"> <input type="submit" value="Search"></form>
    <!-- TODO: Eventually remove signup link, as user will need to be logged in to see the QDB anyway -->
    <hr>
    {% block content %}{% endblock %}
    <script src="{% static 'app/js/jquery-1.11.1.min.js' %}"></script>
    <script src="{% static 'app/js/bootstrap.min.js' %}"></script>
  </body>
</html>

app/templates/app/detail.html
{% extends "app/base.html" %}

{% block content %}
<div id="quote{{quote.id}}">
{% include "app/quote.html" with quote=quote %}
</div>
{% endblock %}

app/templates/app/index.html
{% extends "app/base.html" %}

{% block content %}
{% if page %}
{% for quote in page %}
<div id="quote{{quote.id}}">
  {% include "app/quote.html" with quote=quote %}
</div>
<br>
{% endfor %}
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
    <a href="{% url 'app:index' %}?page={{page.previous_page_number}}">previous</a>
    {% endif %}
    <span class="current">
      Page {{page.number}} of {{page.paginator.num_pages}}.
    </span>
    {% if page.has_next %}
    <a href="{% url 'app:index' %}?page={{page.next_page_number}}">next</a>
    {% endif %}
  </span>
</div>
{% else %}
<p>No quotes have been submitted.</p>
{% endif %}
{% endblock %}

app/templates/app/login.html
{% extends "app/base.html" %}

{% block content %}
<h2>Log In</h2>
{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li{% if message.tags %} class="{{message.tags}}"{% endif %}>{{message}}</li>
  {% endfor %}
</ul>
{% endif %}

<form action="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="Log In">
</form>
{% endblock %}

app/templates/app/quote.html
{% load app_tags %}
<pre>{{quote.text|urlize|target_blank|linebreaks}}</pre>
<small>Submitted by <a href="{% url 'app:user' quote.submitter.username %}">{{quote.submitter.username}}</a> at <a href="{% url 'app:detail' quote.id %}">{{quote.date}}</a></small>
<br>
<small>Tags:</small>
{% if quote.tags %}
<small>
{% for tag in quote.tags.all %}
<a href="{% url 'app:tag' tag.text %}">{{tag.text}}</a>{% if not forloop.last %}, {% endif %}
{% endfor %}
</small>
{% endif %}

app/templates/app/search.html
{% extends "app/base.html" %}

{% block content %}
{% if page %}
<h2>Results for "{{params.q}}"</h2>
{% for quote in page %}
<div id="quote{{quote.id}}">
  {% include "app/quote.html" with quote=quote %}
</div>
<br>
{% endfor %}
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
    <a href="{% url 'app:search' %}?{{path}}&amp;page={{page.previous_page_number}}">previous</a>
    {% endif %}
    <span class="current">
      Page {{page.number}} of {{page.paginator.num_pages}}.
    </span>
    {% if page.has_next %}
    <a href="{% url 'app:search' %}?{{path}}&amp;page={{page.next_page_number}}">next</a>
    {% endif %}
  </span>
</div>
{% else %}
<p>No results for "{{params.q}}"</p>
{% endif %}
{% endblock %}

app/templates/app/signup.html
{% extends "app/base.html" %}

{% block content %}
{% if registered %}
<h2>Success!</h2>
<p>Successfully registered. <a href="{% url 'app:submit' %}">Submit a quote?</a></p>
{% else %}
<h2>Sign Up</h2>
<form action="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="Sign Up">
</form>
{% endif %}
{% endblock %}

app/templates/app/submit.html
{% extends "app/base.html" %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="Submit" />
</form>
{% endblock %}

app/templates/app/tag.html
{% extends "app/base.html" %}

{% block content %}
<h3>Tag: {{tag_text}}</h3>
{% if page %}
{% for quote in page %}
<div id="quote{{quote.id}}">
  {% include "app/quote.html" with quote=quote %}
</div>
{% endfor %}
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
    <a href="{% url 'app:tag' tag_text=tag_text %}?page={{page.previous_page_number}}">previous</a>
    {% endif %}
    <span class="current">
      Page {{page.number}} of {{page.paginator.num_pages}}.
    </span>
    {% if page.has_next %}
    <a href="{% url 'app:tag' tag_text=tag_text %}?page={{page.next_page_number}}">next</a>
    {% endif %}
  </span>
</div>
{% else %}
No quotes found with the tag "{{tag_text}}".
{% endif %}
{% endblock %}

app/templates/app/top.html
{% extends "app/base.html" %}

{% block content %}
<h2>Top Quotes</h2>
{% if page %}
{% for quote in page %}
<div id="quote{{quote.id}}">
  {% include "app/quote.html" with quote=quote %}
</div>
<br>
{% endfor %}
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
    <a href="{% url 'app:top' %}?page={{page.previous_page_number}}">previous</a>
    {% endif %}
    <span class="current">
      Page {{page.number}} of {{page.paginator.num_pages}}.
    </span>
    {% if page.has_next %}
    <a href="{% url 'app:top' %}?page={{page.next_page_number}}">next</a>
    {% endif %}
  </span>
</div>
{% else %}
<p>No quotes have been submitted.</p>
{% endif %}
{% endblock %}

app/templates/app/user.html
{% extends "app/base.html" %}

{% block content %}
<h3>User: {{username}}</h3>
{% if page %}
{% for quote in page %}
<div id="quote{{quote.id}}">
  {% include "app/quote.html" with quote=quote %}
</div>
{% endfor %}
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
    <a href="{% url 'app:user' username=username %}?page={{page.previous_page_number}}">previous</a>
    {% endif %}
    <span class="current">
      Page {{page.number}} of {{page.paginator.num_pages}}.
    </span>
    {% if page.has_next %}
    <a href="{% url 'app:user' username=username %}?page={{page.next_page_number}}">next</a>
    {% endif %}
  </span>
</div>
{% else %}
{{username}} has not submitted any quotes yet.
{% endif %}
{% endblock %}

app/templates/app/user_does_not_exist.html
{% extends "app/base.html" %}

{% block content %}
User "{{username}}" does not exist.
{% endblock %}